### ISSUE TITLE
Wrong format of the machine stamp in the generated .mrc files 

### ISSUE THREAD

**Issue by cgymem17** [ml-struct-bio/cryodrgn#248]
**Describe the bug**
I followed exactly every instruction in the cryoDRGN EMPIAR-10076 tutorial(https://www.notion.so/cryoDRGN-EMPIAR-10076-tutorial-c8728dcc88e744c8827447c3ff094d19) and successfully generated 20 .mrc files as the example does, but all the .mrc files have invalid machine stamp in their header. All the machine stamps are `0x00 0x00 0x00 0x00`, which is not consistent with the requirements in the newest mrcfile documentation(https://mrcfile.readthedocs.io/en/stable/source/mrcfile.html)

**To Reproduce**
After downloading the data, I omitted step 2 and directly get the poses from https://github.com/zhonge/cryodrgn_empiar/blob/main/empiar10076/inputs/cryosparc_P4_J33_004_particles.cs, and then walk through step3-5 to get the wanted 20 .mrc files. 
Below are all the commands I executed:
`cryodrgn parse_pose_csparc cryosparc_P4_J33_004_particles.cs -D 320 -o poses.pkl`
`cryodrgn parse_ctf_csparc cryosparc_P4_J33_004_particles.cs -o ctf.pkl`
`cryodrgn downsample L17Combine_weight_local.mrcs -D 256 -o particles.256.mrcs --chunk 50000`
`cryodrgn downsample particles.256.txt -D 128 -o particles.128.mrcs`
`cryodrgn train_vae data/128/particles.128.mrcs \
										--ctf data/ctf.pkl \
										--poses data/poses.pkl \
										--zdim 8 \
										-n 50 \
										--uninvert-data \ 
										-o tutorial/00_vae128 > tutorial_00.log`
`cryodrgn analyze tutorial/00_vae128 49 --flip --Apix 3.275`

**Expected behavior**
The .mrc files should have been consistent with the standard in the documentation mentioned above, and I think the machine stamp in the headers should be `0x44 0x44 0x00 0x00`. I use a python script in this issue discussion https://github.com/ccpem/mrcfile/issues/4 to update the stamp and get this new machine stamp.

**Additional context**
I have tried to find out why cryoDRGN produces .mrc files with the wrong machine stamp and I found that in line 157, [cryodrgn](https://github.com/zhonge/cryodrgn)/[cryodrgn](https://github.com/zhonge/cryodrgn/tree/master/cryodrgn)/mrc.py, the machine stamp in the class `MRCHeader` (starting from line 26 in the same file) is initialized as `b"\x00" * 4`, which I think can possibly cause the issue. I did not find any other python function to update the machine stamp during the whole .mrc file generating process.

**Comment by vineetbansal** [comment]
Thanks @cgymem17 - So as I understand from the specification, the following line in `mrc.py`:
```
b"\x00" * 4,  # cmap, stamp
```
would need to be changed to something like:
```
b"\x44\x44\x00\x00" if sys.byteorder=='little' else b"\x11\x11\x00\x00"
```
Does that sound right?

**Comment by cgymem17** [comment]
Thank you for your reply. I think it may be the cause of the issue.

**Comment by vineetbansal** [comment]
Ah @cgymem17 - no worries. Let me try to run some validations on my end against the `mrcfile` library (with `permissive=False`), and get this merged in.

**Comment by Guillawme** [comment]
Speaking of `mrcfile`, is there a reason why cryodrgn is not using it? (asking out of curiosity).

**Comment by cgymem17** [comment]
> @cgymem17 - I've fixed the issue in branch `vb/issue248`. Is it possible for you to install `cryoDRGN` from that branch and verify that it fixes your problem before we merge it to the `master` branch?

After re-running the edited version of cryoDRGN, it seems still produces .mrc file with machine stamps `0x00 0x00 0x00 0x00` in my end. What about your running result? Or is there anywhere else in cryoDRGN you reset the machine stamp of the .mrc file?

**Comment by cgymem17** [comment]
Hi @zhonge, 
1. Actually, I just directly edit the mrc.py in cryodrgn environment on my end as @vineetbansal did above. 
2. Thank you for your kind reminder. 
3. I would like to use .mrc file as an input (combined with a .fasta file) of ModelAngelo(https://github.com/3dem/model-angelo) to fit an atomic model (In form of a .cif file).
With the file having incorrect machine stamps, ModelAngelo will just have buggy output saying "unrecognized machine stamp" like below:
<img width="1033" alt="bug1" src="https://user-images.githubusercontent.com/80606153/229587730-2ea87a90-978f-47cc-bedc-c9264f44e812.png">
But when I fixed some of .mrc files produced by cryodrgn using the python script mentioned above, ModelAngelo will produce various buggy output if I put in different .mrc files. 
For example, for edited vol_000.mrc, the gnn training will halt at one-quarter part of the last round with no explicit buggy output.
For edited vol_001.mrc it will have bugs below:
<img width="1408" alt="bug" src="https://user-images.githubusercontent.com/80606153/229584744-044e4f96-4cf4-4c82-ad91-50ce3755afd6.png">
For edited vol_002.mrc it will have bugs below:
[model_angelo.log](https://github.com/zhonge/cryodrgn/files/11141090/model_angelo.log)
These bugs are hard to trace for me due to my limited understanding of MRCFiles, but I tend to think there can be some issues not only invalid machine stamps in the .mrc files produced by cryodrgn when considering the reason for the inconsistency with ModelAngelo, since when I use the EM-map and FASTA sequence from https://www.rcsb.org/structure/7U50, ModelAngelo ran smoothly and produced a reasonable ball-stick model. As one of the authors of cryoDRGN, maybe you can see more information from the buggy output.

**Comment by vineetbansal** [comment]
Hi @cgymem17 - The one-liner I suggested above is necessary, but not sufficient to get around the problem. Since I think you've installed `cryoDRGN` in editable mode (otherwise you wouldn't expect to make changes to `mrc.py` and have it affect any behavior at all), can you try incorporating all the edits at the PR [260](https://github.com/zhonge/cryodrgn/pull/260/files)?

The easiest way to do this, of course, would be to check out the branch.

Let me know if there are any questions.

**Comment by cgymem17** [comment]
Hi @vineetbansal, I have incorporated all the edits in you mentioned (https://github.com/zhonge/cryodrgn/pull/260/files) and I verified that cryodrgn in my end is in editable mode,
<img width="326" alt="截屏2023-04-04 下午4 40 52" src="https://user-images.githubusercontent.com/80606153/229915425-0fb1492b-fc1e-4cc8-8dfc-c429f9331b18.png">
but after re-running `cryodrgn analyze`, the .mrc file produced is still with machine stamps `0x00 0x00 0x00 0x00`
![image](https://user-images.githubusercontent.com/80606153/229916516-7e63f1bd-66e0-411c-bbb9-7c7819812390.png)

**Comment by vineetbansal** [comment]
@cgymem17 - thanks for trying out the edits. Just so we're on the same page - modifying the code will of course not touch any `.mrc` files that you've already generated. Are you saying that when you now perform this step:
```
cryodrgn downsample L17Combine_weight_local.mrcs -D 256 -o particles.256.mrcs --chunk 50000
```
The resulting `particles.256.mrcs` file still fails `mrcfile` validation? Or is there some other `cryoDRGN` step you're doing that's generating these unusable `.mrc` files?

**Comment by cgymem17** [comment]
@vineetbansal What I am saying is, after I incorporate the edits you mentioned above, I just directly run `cryodrgn analyze` as @zhonge said above to regenerate .mrc files but not re-run
`cryodrgn downsample L17Combine_weight_local.mrcs -D 256 -o particles.256.mrcs --chunk 50000`.
I only re-run the whole process when I just do the one-liner edit of the cryodrgn. Do you think I have to re-run the whole process after incorporating the edits?

**Comment by vineetbansal** [comment]
@cgymem17 - ah, yes you did mention that above. That makes sense. No - you shouldn't have to re-run the previous steps. `cryodrgn analyze` will generate the volume `.mrc` files. Let me check a few things on my end and see if there's a code path that I missed.

**Comment by cgymem17** [comment]
@vineetbansal - Thanks for your advice, I also think the updated version of cryodrgn was never used and I will try putting in `raise RuntimeError`. Or which time slot from this Friday to next Monday is convenient for you to have a Zoom call? I am available all the time except for 2-5 pm this Friday. Really appreciate your help!
